services:
  responsi_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: responsi_api:latest
    container_name: responsi_api
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - mysql_network
    restart: unless-stopped

  responsi_api_ngin:
    image: nginx:alpine
    container_name: responsi_api_nginx
    ports:
      - "127.0.0.1:9003:80"
    networks:
      - mysql_network
    volumes:
      - ./:/var/www/html  # Mount Laravel project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx config
    depends_on:
      - responsi_api
    restart: always

networks:
  mysql_network:
    external: true